### ISSUE TITLE
Update the run manager

### ISSUE THREAD

**Issue by ThibeauWouters** [kazewong/jim#112]
Here is some things we might want to add to the run manager:

- [x] Compute the SNR and save it somewhere. 
- [ ] Maybe add support for an SNR threshold, to skip injections below this threshold. See [this example script](https://github.com/ThibeauWouters/TurboPE-BNS/blob/main/injections/injection_recovery.py) 
- [ ] Add support to randomly sample injection parameters from the given prior ranges if no injection parameters are given.
- [x] Plotting functionalities (see #107 for work in progress)
- [ ] Add functionality to save everything in the runmanager: hyperparameters, save the output chains separately. 
- [ ] Add flexible functionality for loading from other RunManagers, e.g., load the injection parameters of a previous run in case the user wants to play around with hyperparameters on a specific injection
- [ ] Add command line functionalities (see #18 as well)
- [ ] Check how to handle real GW events, load data, preprocess it et cetera. 
- [ ] Add dedicated examples of the runmanager
- [x] Add functionality to for doing multiple event runs in a batch (see #145 )

**Comment by zipengwang98** [comment]
pushed a new commit that stores SNR

**Comment by ThibeauWouters** [comment]
@zipengwang98 where exactly? I don't see it

**Comment by thomasckng** [comment]
I think he meant [this commit](https://github.com/kazewong/jim/commit/ee08171aeb855c92a1c9dfdbcefb65ceea15e1db)
